# Homework 1: 

##  Introduction to Machine Learning for Machine Learning Zoomcamp 2024
___

#### Downloainding the data from the link provided in the homework description

In [16]:
# Import the library
import pandas as pd
import numpy as np


import requests

# URL of the file to be downloaded
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'

# Send a GET request to the URL
response = requests.get(url)

# open the file in write binary mode
with open('laptops.csv', 'wb') as file:
        file.write(response.content)



####  Import the pandas library


In [17]:
import pandas as pd
pd.__version__

'2.2.2'

In [18]:
# import the data into a DataFrame and assign it to the variable df
df = pd.read_csv('laptops.csv', encoding='latin-1')
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [19]:
# checking info about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


____

####  Question 1. Pandas version (1 point)

In [30]:
# Question 1. Pandas version (1 point)
pd.__version__

'2.2.2'

#### Question 2. How many records are in the dataset?

In [31]:
# Question 2. Records count (1 point) Number of rows in the dataset
num_columns = df.shape[0]
print(num_columns)

2160


#### Question 3.How many laptop brands are presented in the dataset?

In [32]:
# Question 3. Laptop brands (1 point)
df.nunique()


Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            30
Touch              2
Final Price     1440
dtype: int64

#### Question 4.How many columns in the dataset have missing values?

In [33]:
# Question 4. Missing values (1 point)
missing_values = df.isnull().sum()
missing_values

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             0
Touch              0
Final Price        0
dtype: int64

#### Question 5. What's the maximum final price of Dell notebooks in the dataset?

In [34]:
# Group by 'Brand' and get the maximum 'Final Price' for each brand
max_prices = df.groupby('Brand')['Final Price'].max()

# Select the maximum price for the 'Dell' brand and convert it to an integer
max_price_dell = int(max_prices['Dell'])

# Print the result
print(max_price_dell)

3936


####  Question 6. Median value of Screen (1 point)

- Find the median value of Screen column in the dataset.
- Next, calculate the most frequent value of the same Screen column.
- Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
- Now, calculate the median value of Screen once again.
- Has it changed?

In [35]:
# Find the median value of Screen column in the dataset.
median_screen = df['Screen'].median()
median_screen

15.6

In [36]:
# Next, calculate the most frequent value of the same Screen column.
most_frequent_screen = df['Screen'].mode()
most_frequent_screen

0    15.6
Name: Screen, dtype: float64

In [27]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
df['Screen'] = df['Screen'].fillna(0)

# Check if there are any missing values left in the Screen column.
missing_values_screen = df['Screen'].isnull().sum()

df.isna().sum()


Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             0
Touch              0
Final Price        0
dtype: int64

In [28]:
# Now, calculate the median value of Screen once again.
median_screen = df['Screen'].median()
median_screen

15.6

#### Question 7. Sum of weights (1 point)

- Select all the "Innjoo" laptops from the dataset.
- Select only columns RAM, Storage, Screen.
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Compute the inverse of XTX.
- Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the sum of all the elements of the result?

In [53]:
# Select all the "Innjoo" laptops from the dataset.
innjoo_laptops = df[df['Brand'] == 'Innjoo']
innjoo_laptops


Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [54]:
# Select only columns RAM, Storage, Screen.

from pyparsing import col


column_select = ['RAM', 'Storage', 'Screen']

# Select column_select from the "Innjoo" laptops  dataset.
data = innjoo_laptops[column_select]
data


RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [42]:
# Get the underlying NumPy array. Let's call it X.
X = data.values

# Print the NumPy array,and check the shape of the array.
print(X)
print(X.shape)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]
(6, 3)


In [43]:
# compute the transpose of the NumPy array X and assign it to the variable X_tranpose.
X_tranpose = X.T

# Print the transposed array, and the shape of the transposed array.
print(X_tranpose)
print(X_tranpose.shape)

[[  8.    8.    4.    6.    6.    6. ]
 [256.  512.   64.   64.  128.  128. ]
 [ 15.6  15.6  14.1  14.1  14.1  14.1]]
(3, 6)


In [45]:
# Compute matrix-matrix multiplication between the transpose of X and X to get a square matrix
XTX = X_tranpose @ X
print(XTX)

# shape of the resulting matrix
shape_XTX = XTX.shape
shape_XTX

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


(3, 3)

In [46]:
# Compute the inverse of the XTX array and assign it to the variable XTX_inv
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [48]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [52]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = XTX_inv @ X_tranpose @ y
print(w)

[45.58076606  0.42783519 45.29127938]


In [51]:
# - What's the sum of all the elements of the result?

sum_w = w.sum()
print(sum_w)

91.2998806299557
